apiVersion: v1 
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
    app: demo-voting
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env: # Not recommended way to set user and password, we must use secrets
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust 