apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-14T10:46:00Z"
  name: webapp-service
  namespace: default
  resourceVersion: "544"
  uid: 4f1655f1-2f74-4e22-bf7c-644db3beee32
spec:
  clusterIP: 172.20.100.99
  clusterIPs:
  - 172.20.100.99
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: simple-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

